---

- import_playbook: archivebox/main.yml
- import_playbook: audiobookshelf/main.yml
- import_playbook: bedrock/main.yml
- import_playbook: bento-pdf/main.yml
- import_playbook: beszel/main.yml
- import_playbook: calibre-web/main.yml
- import_playbook: changedetection/main.yml
- import_playbook: dispatcharr/main.yml
- import_playbook: excalidraw/main.yml
- import_playbook: gatus/main.yml
- import_playbook: gitea/main.yml
- import_playbook: gotify/main.yml
- import_playbook: grafana/main.yml
- import_playbook: homepage/main.yml
- import_playbook: igotify/main.yml
- import_playbook: immich/main.yml
- import_playbook: invidious/main.yml
- import_playbook: jellyfin/main.yml
- import_playbook: jellyseerr/main.yml
- import_playbook: kiwix/main.yml
- import_playbook: lidarr/main.yml
- import_playbook: lubelogger/main.yml
- import_playbook: maloja/main.yml
- import_playbook: miniflux/main.yml
- import_playbook: navidrome/main.yml
- import_playbook: openclaw/main.yml
- import_playbook: prowlarr/main.yml
- import_playbook: qbittorrent/main.yml
- import_playbook: qui/main.yml
- import_playbook: radarr/main.yml
- import_playbook: rfd-fyi/main.yml
- import_playbook: romm/main.yml
- import_playbook: searxng/main.yml
- import_playbook: sonarr/main.yml
- import_playbook: speedtest-tracker/main.yml
- import_playbook: umami/main.yml
- import_playbook: vaultwarden/main.yml
- import_playbook: watchyourlan/main.yml
