- name: Install gpg
  apt:
    name:
      - gpg
    state: present
    update_cache: yes

- name: Ensure /etc/apt/keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Grafana GPG key
  get_url:
    url: https://apt.grafana.com/gpg-full.key
    dest: /etc/apt/keyrings/grafana.asc
    mode: '0644'

- name: Add Grafana APT repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/grafana.asc] https://apt.grafana.com stable main"
    filename: grafana
    state: present

- name: Install alloy
  apt:
    name:
      - alloy
    state: present
    update_cache: yes

- name: Ensure docker group exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Add alloy user to docker group
  ansible.builtin.user:
    name: alloy
    groups: docker
    append: yes

- name: Create /etc/alloy directory
  file:
    path: /etc/alloy
    state: directory
    mode: '0755'

- name: Deploy Alloy configuration file
  copy:
    dest: /etc/alloy/config.alloy
    content: |
      loki.relabel "journal" {
        forward_to = []

        rule {
          target_label  = "host"
          replacement   = constants.hostname
        }

        rule {
          source_labels = ["__journal__systemd_unit"]
          target_label  = "unit"
        }
      }

      loki.source.journal "read"  {
        forward_to    = [loki.write.endpoint.receiver]
        relabel_rules = loki.relabel.journal.rules
        labels        = {component = "loki.source.journal"}
      }

      loki.relabel "docker" {
        forward_to = []

        rule {
          target_label  = "host"
          replacement   = constants.hostname
        }
        rule {
          source_labels = ["__meta_docker_container_name"]
          regex         = "/(.*)"
          target_label  = "container"
        }
      }

      discovery.docker "linux" {
        host = "unix:///var/run/docker.sock"
      }

      loki.source.docker "default" {
        host       = "unix:///var/run/docker.sock"
        targets    = discovery.docker.linux.targets
        labels     = {"app" = "docker"}
        relabel_rules = loki.relabel.docker.rules
        forward_to = [loki.write.endpoint.receiver]
      }

      loki.write "endpoint" {
        endpoint {
          url = "{{ loki_url }}"
        }
      }
    mode: '0644'
    backup: yes

- name: Enable and start alloy
  systemd:
    name: alloy
    daemon_reload: yes
    enabled: true
    state: restarted
