services:
  bentopdf:
    image: ghcr.io/alam00000/bentopdf:2.2.0
    container_name: bentopdf
    restart: always
    networks:
      - bentopdf
  newt:
    image: docker.io/fosrl/newt:1.9.0
    container_name: newt-bentopdf
    restart: unless-stopped
    networks:
      - bentopdf
    environment:
      - PANGOLIN_ENDPOINT={{ pangolin_endpoint }}
      - NEWT_ID={{ bentopdf_newt_id }}
      - NEWT_SECRET={{ bentopdf_newt_secret }}
networks:
   bentopdf:
     name: bento-pdf
