services:
  rfd-fyi:
    image: ghcr.io/davegallant/rfd-fyi
    container_name: rfd-fyi
    networks:
      - rfd-fyi
    restart: unless-stopped
  newt:
    image: docker.io/fosrl/newt:1.10.1
    container_name: newt-rfdfyi
    restart: unless-stopped
    networks:
      - rfd-fyi
    environment:
      - PANGOLIN_ENDPOINT={{ pangolin_endpoint }}
      - NEWT_ID={{ rfdfyi_newt_id }}
      - NEWT_SECRET={{ rfdfyi_newt_secret }}

networks:
  rfd-fyi:
    name: rfd-fyi
